stages:
  - pages
  - deploy

deploy:
  stage: deploy
  image: curlimages/curl:latest
  only:
    - tags
  except:
    - branches
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'

make-documentation:
  stage: pages
  image: docker:19
  services:
    - docker:19-dind
  variables:
    DOCKER_HOST='tcp://localhost:2375'
  script:
    - 'ls -la'
    - 'docker pull ghcr.io/t3docs/render-documentation:develop'
    - 'docker tag ghcr.io/t3docs/render-documentation:develop render-documentation:develop'
    - 'source <(docker run --rm ghcr.io/t3docs/render-documentation:develop show-shell-commands)'
    - 'dockrun_t3rd makehtml'
    - 'ls -la'
    - 'mv Documentation-GENERATED-temp/Result/project/0.0.0 public'
    - 'ls -la'
  artifacts:
    when: on_success
    paths:
      - public
