stages:
  - pages
  - deploy

deploy:
  stage: deploy
  image: curlimages/curl:latest
  only:
    - tags
  except:
    - branches
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'

make-documentation:
  stage: pages
  image:
    name: ghcr.io/t3docs/render-documentation:develop
    entrypoint: ["/bin/bash"]
  before_script:
    - 'ls -la'
    - 'mkdir Documentation-GENERATED-temp'
  script:
    - 'ls -la'
    - '/bin/bash /ALL/Menu/mainmenu.sh makehtml'
