services:
  SUDHAUS7\Sudhaus7Wizard\Command\RunWizardCommand:
    arguments:
      $name: 'wizard:run'
    tags:
      - name: 'console.command'
        command: 'wizard:run'
        schedulable: true

  SUDHAUS\Sudhaus7Wizard\Command\ShowInformationCommand:
    arguments:
      $name: 'wizard:info'
    tags:
      - name: 'console.command'
        command: 'wizard:info'
        schedulable: false

  SUDHAUS7\Sudhaus7Wizard\Command\ListNextCommand:
    arguments:
      $name: 'wizard:list'
    tags:
      - name: 'console.command'
        command: 'wizard:list'
        schedulable: false

  SUDHAUS7\Sudhaus7Wizard\Process\WizardProcessRegistry:
    arguments:
      - !tagged_iterator { tag: 'wizard.process' }
