services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  SUDHAUS7\Sudhaus7Wizard\:
    resource: '../Classes/*'
  SUDHAUS7\Sudhaus7Wizard\CreateProcess:
    public: true
  SUDHAUS7\Sudhaus7Wizard\Cli\Run:
    tags:
      - name: 'console.command'
        command: 'sudhaus7:wizard'
        description: 'run wizard tasks'
        schedulable: true
  SUDHAUS7\Sudhaus7Wizard\EventHandlers\PreSysFileReferenceEventHandler:
    tags:
      - name: event.listener
        identifier: 's7wizardBaseHandleSysFileReferences'
  SUDHAUS7\Sudhaus7Wizard\EventHandlers\FinalTTContentFormFrameworkListener:
    tags:
      - name: event.listener
        identifier: 's7wizardBaseFinalTTContentFormFrameworkListener'
